### ISSUE TITLE
Nota sobre Mozilla Thunderbird (para revisión)

### ISSUE THREAD

**Issue by Anteojudo** [mozillahispano/noticias#10]
Estoy escribiendo la note que había prometido sobre Thunderbird, disculpen si he tardado pero es que lo estuve usando y estube con la universidad a full estas últimas semanas.
¡Saludos!

**Comment by Anteojudo** [comment]
¡Hola chicos!
He aquí el borrador listo para revisión en Wordpress, espero sea encaminado lo que he escrito --> https://www.mozilla-hispano.org/wp-admin/post.php?post=39289&action=edit
Saludos :)

**Comment by stripTM** [comment]
Le he dado un repaso rápido para hacer pequeñas correcciones.

**Comment by Anteojudo** [comment]
¡Genial @stripTM! Espero que te haya interesado el escrito :)
¡Saludos!

**Comment by yuniers** [comment]
@Anteojudo revisado y programado para hoy a las 8 UTC. Muchas gracias, sobre todo por tus ideas acerca de la seguridad.
En clases aprendí que cifrar no es el mejor término para referirse  a ocultar la información y que es mejor usar encriptar, muchas personas utilizan cifrar. En el artículo dejé en alguna ocasiones cifrar pues referencias un artículo de una universidad.

**Comment by Anteojudo** [comment]
Hola @yuniers, muchas gracias. La verdad que debe ser costumbre porque siempre usé cifrar, de ahora en más utilizo encriptar. :9
Igual como en el post que utilizo estaba igual no se me habían generado dudas. no fue con intención, lo prometo. (Además el link que ofrezco está muy bueno para tener un panorama, ¿a vos  qué te pareció?)

**Comment by yuniers** [comment]
No no hay problema con eso. Esta abarcador y orienta a las personas en ese tema, las opiniones están buenas.
