### ISSUE TITLE
Reseña sobre Firefox OS Addons

### ISSUE THREAD

**Issue by CodingFree** [mozillahispano/noticias#11]
Breve reseña sobre Addons para Firefox OS y promoción del Meetup del 24 de septiembre en Madrid, España.

**Comment by yuniers** [comment]
Hola @CodingFree
¿Necesitas ayuda para terminar el artículo? Podemos ayudarte con eso!

**Comment by CodingFree** [comment]
La verdad es que sí, no te voy a engañar. Llevo desde el fin de semana sentado en una silla programando y no me quedan suficientes retinas como para continuar con el artículo... estoy algo esclavizado por aquí :(

**Comment by CodingFree** [comment]
Aunque ahora que lo pienso, quizás tendríamos que posponer el ar´ticulo un par de semanas porque ahora mismo se está haciendo la Beta de los Addons en el Marketplace, así que casi habría que aprovechar el lanzamiento oficial :dancer:

**Comment by yuniers** [comment]
Esta bien, creo que @pochy-ja podría ayudarte, le conoce mas acerca del tema. Podrían intercambiar ideas y así logran terminar la noticia que esta muy interesante

**Comment by CodingFree** [comment]
@pochy-ja estoy por Telegram, ¿Qué te parece si hablamos por ahí?

**Comment by pochy-ja** [comment]
De momento en mi conexión regular a internet bloquearon telegram, solo me conecto en otras ocasiones por otro lugar pero no es muy frecuente, si tienes algo adelantado compártemelo en un gdoc, litepad o lo que te convenga para echarle un ojo haber que tienes y terminarlo, aunque vamos un poco tarde para hablar del meetup del 24 de septiembre, :speak_no_evil:

**Comment by CodingFree** [comment]
Ya lo importante no es el Meetup, sino que dentro de poco será posible subir addons al Marketplace.

**Comment by pochy-ja** [comment]
:smile: Lo sé, pásame lo que tengas y lo vamos viendo, tenemos usos horarios parecidos ahora? o es que estas a tope programando hasta de madrugada!

**Comment by yuniers** [comment]
@CodingFree podrías decirme donde está el artículo para publicarlo en MH o prefieres subirlo tu?
