### ISSUE TITLE
Protección de rastreo - Actualización Beta

### ISSUE THREAD

**Issue by deimidis** [mozillahispano/noticias#12]

**Comment by deimidis** [comment]
El temario:

# Más protección en Firefox
- Primer párrafo en que se agrega la Protección de rastreo en el modo de navegación privada
- ¿qué es el rastreo?
  - En Internet solo se hace dineron con la publicidad
  - La mejor forma de vender publicidad es a través de saber el comportamiento de las personas mientras navegan
- Cómo funciona la protección de rastreo de Firefox
  - Comparativa Clarin, La Nación y Genbeta
- Diferencias con un bloqueador de publicidad
- Cómo probarlo

**Comment by yuniers** [comment]
Muchas gracias Guille, la protección anti rastreo es lo mejor
