### ISSUE TITLE
Traducción del artículo "Mozilla’s Vision for a Healthy, Sustainable Web"

### ISSUE THREAD

**Issue by Anteojudo** [mozillahispano/noticias#13]
Estoy en este momento en la traducción de esta nota de opinión: https://blog.mozilla.org/blog/2015/09/24/mozillas-vision-for-a-healthy-sustainable-web/#more-9036
Cualquier duda o problema que surja les avisaré a todos. Por el momento la nota va encaminada.

**Comment by francjp** [comment]
Genial, gracias por avisar ;)... supongo que @yuniers también está al tanto

**Comment by yuniers** [comment]
Si @francjp , hoy la vi e hice pequeño ajustes, cuando termines nos avisas para publicarla @Anteojudo

**Comment by Anteojudo** [comment]
¡Hola chicos!
La nota ya está para revisión, espero puedan leerla y corregirla para que se pueda publicar sin problemas. 
¡Saludos! :)

**Comment by yuniers** [comment]
Revisado y publicado! Muchas gracias @Anteojudo
