### ISSUE TITLE
Traducir el artículo: Proposed Principles for Content Blocking

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/noticias#14]

**Comment by nukeador** [comment]
Joel está con ello aquí:

https://docs.google.com/document/d/1rVotlsQHOYstWP1Fn-0fu2f3UPI_HT9yW0ztfaNDGzo/edit?usp=sharing

**Comment by JoelBuenrostro** [comment]
Creo que ya esta bien el documento para que se pase a revisión, si hay algo mal lo corrijo

**Comment by yuniers** [comment]
Revisado y publicado. Joel te he creado una cuenta en el blog para que salga a tu nombre.
Muchas gracias @ JoelBuenrostro

**Comment by JoelBuenrostro** [comment]
Excelente, para poder apoyar en futuras redacciones
