### ISSUE TITLE
Nota sobre NPAPI en Firefox

### ISSUE THREAD

**Issue by Anteojudo** [mozillahispano/noticias#15]
Hola chicos! Hace unos días ha salido una publicación sobre NPAPI en Firefox. La nota es interesante en el sentido que habla sobre los progresos del navegador en post de desprenderse de Flash, pero no sé si es relevante para noticias. 
¿Qué opinan ustedes? Ya la nota está escrita en wordpress por si las dudas.

**Comment by yuniers** [comment]
Ya está revisada y programada para dentro de poco.
Muchas gracias @Anteojudo

**Comment by Anteojudo** [comment]
¡De nada Yunier! :)
