### ISSUE TITLE
Artículo Firefox 42

### ISSUE THREAD

**Issue by yuniers** [mozillahispano/noticias#17]
Noticia sobre las novedades de Firefox 42. Aquí están algunas de las funcionalidades que veremos https://www.mozilla.org/en-US/firefox/42.0beta/releasenotes/

**Comment by deimidis** [comment]
Como este es uno de los lanzamientos importantes del año, habrá que ver el foco de Mozilla, que en este caso será obviamente acerca de seguridad y la protección contra rastreo. No digo que solo nos centremos en eso, pero habría que dedicarle espacio (aunque ya hablamos de eso en anteriores notas)

**Comment by yuniers** [comment]
Hola Guille.
Tienes toda la razón, ese sera el principal tema, también voy a  abordar las demás características y voy a escribir acerca de la versión de 64 bits para Windows aunque no se si por fin la liberen.

**Comment by pochy-ja** [comment]
@yuniers averigua bien, porque la versión de 64 bits de windows la estaban retrasando porque algunas cosas no funcionaban bien en ella, aunque como este lanzamiento es importante quisás lo hayan resuelto.

**Comment by pochy-ja** [comment]
Parece que planean habilitarlas en la 42, este bug[1] está listo para habilitarlas, pero en este [2] dicen que estan esperando por un partner para poder habilitarlas!

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1180792
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1181014#c24

**Comment by yuniers** [comment]
Vamos a ver, aunque creo que si la lanzarán porque esta compilada en las dos builds candidatas a la final http://ftp.mozilla.org/pub/firefox/candidates/42.0-candidates/

De todas maneras escribiré sobre ello y si la quitan lo dejo para la próxima
