### ISSUE TITLE
Nota sobre eliminación de Panorama

### ISSUE THREAD

**Issue by yuniers** [mozillahispano/noticias#19]
Panorama será eliminado de Firefox y sería bueno escribir acerca de esto https://bugzilla.mozilla.org/show_bug.cgi?id=836758

**Comment by pochy-ja** [comment]
Como lo tienes asignado supongo que la vas a escribir, entonces, como recomendación creo que estás en el bug incorrecto, en ese bug se tenía pensado eliminar y crear un complemento para mantener la funcionalidad pero desacoplado de firefox porque tenia problemas de estabilidad o algo, ahora mismo lo han cerrado como WONTFIXED y está este [1] actual que lo que se maneja es migrar lo que la gente tenga agrupado y tal para carpetas de marcadores o ventanas abiertas en sí, segun las estadisticas el uso es muy bajo como para considerarlo relevante, aunque el cambio para el que lo use va a ser fuerte, aunque se está trabajando en master(45) ahora mismo, sería importante escribir algo como guía para que la gente esté informada, aunque vi alguien pidiendo el código de lo que se tenía pensado hacer para moverlo a un addon, por lo que hay idea de seguir teniendo la funcionalidad pero por parte comunitaria supongo!

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1221050

**Comment by yuniers** [comment]
Esta bien, voy a escribirle a alguien de Mozilla a ver que me dice
