### ISSUE TITLE
Nueva versión de Firefox

### ISSUE THREAD

**Issue by francjp** [mozillahispano/noticias#2]
https://wiki.mozilla.org/RapidRelease/Calendar

Repite cada 6 semanas

**Comment by Anteojudo** [comment]
Hola Fran! ¿Tecnicamente tendríamos que escribir algo sobre Firefox 40 en Windows 10 hoy, o me equivoco? 
Saludos.

**Comment by deimidis** [comment]
Si, él lo hizo, lo dejó como borrador y yo lo revisé. Ahora se me ocurre que deberíamos poner un enlace más rápido al artículo sobre como volverlo predeterminado nuevamente (hay un video de los chicos de Perú también)

**Comment by Anteojudo** [comment]
¿Y eso cómo se podría hacer? ¿No podríamos poner un párrafo en el artículo de Fran que enlace ese video para que sea un combo?

**Comment by francjp** [comment]
Creo que lo del video no es muy público realmente.
Yo enlazaría con el artículo de SUMO directamente

**Comment by Anteojudo** [comment]
Sí, opino lo mismo. Aquí está el enlace artículo de SUMO: https://support.mozilla.org/es/kb/como-cambiar-tu-navegador-predeterminado-en-win10
