### ISSUE TITLE
MozFest 2015

### ISSUE THREAD

**Issue by yuniers** [mozillahispano/noticias#20]
Artículo sobre MozFest 2015 https://blog.mozilla.org/blog/2015/11/09/mozfest-2015-connecting-leaders-and-rallying-communities-for-the-open-web/

**Comment by Shiknot** [comment]
El pasado fin de semana, el sexto Mozfest anual — celebración de Mozilla de la Web abierta — convocó hackers, profesores y organizadores de todo el mundo para abordar algunos de los problemas más urgentes que enfrenta la Web hoy en día. Juntos, vimos la forma en la que podemos actuar como líderes en las esferas tecnológica, política y social para crear una mejor Web para todos.
Los participantes de diversos campos como el periodismo, la educación, la ciencia, la promoción, el hardware y el Internet de las cosas trabajaron en colaboración, en sesiones auto-organizadas para dar forma al futuro de la Web. Con 1.700 asistentes procedentes de casi todos los rincones de la Tierra en la asistencia, 300 sesiones de voluntariado organizado y 50 itinerarios de aprendizaje, el fin de semana fue una divertida celebración de invitar a la conciencia — y un recordatorio sobre que todos nosotros tenemos la habilidad de movilizar a otros y potenciar el avance de la Web abierta.
 <img class="alignnone size-large wp-image-9074" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22428447538_57e82a297c_o-600x400.jpg" alt="22428447538_57e82a297c_o" height="400" width="600">
Para dar comienzo con una feria de ciencias y terminando con una fiesta muestra las creaciones que fueron hackeadas en colaboración, el fin de semana fue una tremenda, cacofónica celebración inventando, construyendo y forjando vínculos con nuevos aliados de todo el mundo. Ver fotos del fin de semana <a href="https://www.flickr.com/photos/134771568@N06/albums/with/72157658567152683">aquí</a>.
Sesiones propuestas por participantes nos permitieron excavar en los problemas más importantes para la comunidad de la Web Abierta. En el Espacio de los Ciudadanos Digitales, participantes exploraron el estado de la privacidad online, la vigilancia y los derechos digitales — y hackeado en construir una Web más segura. La Senior Manager de Politica de Mozilla, Reagan MacDonald remarcó actuales amenazas a la Web segura, como el Proyecto de Ley de Facultades de Investigación del Reino Unido, que recolecta, analiza y almacena datos de usuarios.
 <a href="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22455735387_fa689c6ca0_o.jpg"><img class="alignnone size-large wp-image-9075" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22455735387_fa689c6ca0_o-600x400.jpg" alt="22455735387_fa689c6ca0_o" height="400" width="600"></a>
MacDonald incluso tocó puntos brillantes: los realizadores, pensadores e ingenieros dedicando tiempo y energía en solutciones. “En mi mundo ideal, privacidad y seguridad son la configuración predeterminada” dijo0 MacDonald.
Durante MozFest, jóvenes aprendices y líderes expusieron sus proyectos. George, de 12 años de edad de Kent, Inglaterra, construyó “El Guante” — un curso interactivo de carreras impulsado por Raspberry Pi, Makey Makey, Bluetooth, sensores de movimiento y Python. George enseñó codificación y electrónica básica a más de 100 compañeros en el fin de semana. Vecino, Otis de 8 años mostró su más reciente creación: un juego de simulación virtual de vuelo.
 <a href="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/Screen-Shot-2015-11-09-at-5.12.00-PM.png"><img class="alignnone size-large wp-image-9076" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/Screen-Shot-2015-11-09-at-5.12.00-PM-600x444.png" alt="Screen Shot 2015-11-09 at 5.12.00 PM" height="444" width="600"></a>
Próximo, participantes debatieron sobre temas como hardware abierto y el Internet de las cosas. El equipo en <a href="https://www.wevolver.com/">Wevolver</a> mostró un proyecto robótico de código abierto que ayudaría a niños enfermos a visitar remotamente el Zoológico de Londres. Los jóvenes serán capaces de ponerse un casco de realidad virtual y experimentar el zoológico a través de los ojos del robot, interactuando con los animales y las exhibiciones. 
 <a href="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22836694332_40a42f5ed1_o.jpg"><img class="alignnone size-large wp-image-9077" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22836694332_40a42f5ed1_o-600x400.jpg" alt="22836694332_40a42f5ed1_o" height="400" width="600"></a>
“Nosotros queremos demostrarle a la gente que el movimiento del hardware abierto existe” dijo Bram Geener de Wevolver. “Lo que pasa en software puede pasar en hardware.”
Bajando al hall, participantes debatieron un <a href="http://www.iotmanifesto.com/">Manifiesto del Diseño del internet de las cosas</a>, que busca inspirar ingenieros a crear dispositivos seguros, privados y útiles. 
Entonces, ¿qué viene después? ¿Cómo llevamos el impulso de MozFest en los esfuerzos que sean productivos, creativos y construido usando el ethos abierto que es tan esencial para la Web? En Mozilla, nosotros sobrecargaremos lo que hemos hecho en los últimos días — y aprendido en los últimos años — construyendo más comunidades y eventos alrededor del mundo. Presentaremos más oportunidades para cultivar líderes. Y permitiremos a todos, desde jóvenes líderes a ejecutivos, para alimentar aún más el movimiento
 <a href="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22885142291_383827e7da_o.jpg"><img class="alignnone size-large wp-image-9078" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/22885142291_383827e7da_o-600x400.jpg" alt="22885142291_383827e7da_o" height="400" width="600"></a>
¿Qué sobre vos?  Las ideas generadas en MozFest 2015 demostraron que juntos, somos una fuerza formidable, y que nos estamos haciendo más fuertes. Las soluciones a las cuestiones urgentes relacionadas con la privacidad y la vigilancia, inclusión digital, el internet de las cosas y más están a nuestro alcance. Mantengámonos haciendo ruido, y reunamos más personas en torno a estas causas. Así es como nos defendemos la Web. <a href="https://www.mozilla.org/en-US/contribute/">Únete a nosotros</a>.
Blog posteado por David Bryant, VP of Platform Engineering and Interim CTO:
<a href="https://blog.mozilla.org/blog/2015/11/09/mozfest-2015-demo-garage-showing-whats-possible-with-the-open-web/">MozFest 2015 Demo Garage: Showing What’s Possible with the Open Web</a>

**Comment by yuniers** [comment]
Muchas gracias @Shiknot 
Revisado y publicado

**Comment by Shiknot** [comment]
No pude loguear en el foro,por eso respondi en github

-----Mensaje original-----
De: "Yunier J. Sosa Vázquez" notifications@github.com
Enviado: ‎16/‎11/‎2015 17:31
Para: "mozillahispano/noticias" noticias@noreply.github.com
CC: "Juan Manuel" jm.bustafan@gmail.com
Asunto: Re: [noticias] MozFest 2015 (#20)

Muchas gracias @Shiknot 
Revisado y publicado

**Comment by yuniers** [comment]
No hay problema @Shiknot , creo que por esta vía es mejor.
