### ISSUE TITLE
Liberación Firefox para iOS

### ISSUE THREAD

**Issue by yuniers** [mozillahispano/noticias#21]
Hace pocas horas Mozilla liberó Firefox para iOS https://blog.mozilla.org/blog/2015/11/11/firefox-users-can-now-choose-their-favorite-browser-on-ios/

**Comment by Shiknot** [comment]
Si eres usuario de iPhone, iPad o iPod Touch serás feliz de saber que <a href="http://itunes.apple.com/app/id989804926">Firefox para iOS está disponible en la App Store de todo el mundo.</a>
Firefox para iOS te permite llevar tu navegador favorito contigo con todas las características que ya amas, incluyendo búsqueda inteligente y flexible, manejo intuitivo de pestañas, sincronización con cuentas de Firefox y Busqueda Privada.
Puedes usar cuentas de Firefox para sincronizar tu historial de búsqueda, pestañas y contraseñas; y señaladores desde otros dispositivos a Firefox para iOS.

https://www.youtube.com/watch?v=HoAtBKmNUEY

• Sugerencias de búsqueda predice que estás buscando en tu motor de búsqueda favorito.
• Pistañas visibles te permiten manejar fácilmente multiples pestañas en la misma pantalla.
• Busqueda Privada te brinda la habilidad de navegar la Web sin guardar historial o compratir cookies existentes con otros sitios que visites 
<img class="shrinkToFit transparent" alt="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/FFx-iOS_PR-Mockup_Release-EN_Web.png" src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/FFx-iOS_PR-Mockup_Release-EN_Web.png" height="299" width="167">
Para tener un acceso más fácil a Firefox en tu dispositivo iOS puedes anclarlo en la parte inferior de tu pantalla principal. 
Espero que disfruten la primera versión de Firefox para iOS, y espero ver mucho más de nosotros pronto ya que vamos a toda velocidad entregando en forma continua nuevas características. Estoy orgulloso del equipo por llevarnos a donde estamos hoy y ansioso de ver donde estaremos en el futuro.
Gracias por probarnos
