### ISSUE TITLE
Artículo sobre el rastreo y la privacidad

### ISSUE THREAD

**Issue by yuniers** [mozillahispano/noticias#22]
https://blog.mozilla.org/blog/2015/12/01/visualizing-the-invisible/

Quizás este articulo podríamos mejorarlo con este video http://mzl.la/1TlvvOS

**Comment by Anteojudo** [comment]
Hola Yunier, ya me encargo del artículo.

**Comment by yuniers** [comment]
Muchas gracias @Anteojudo por acceder a hacerlo.
Cuando lo tengas listo por favor avísame.

**Comment by Anteojudo** [comment]
Ya casi está, en unos minutos lo dejo para revisión :)

**Comment by Anteojudo** [comment]
Hola @yuniers , el texto ya está para revisión. ¡Saludos!

**Comment by yuniers** [comment]
Perdón por la demora @Anteojudo. La semana pasada estaba complicado en el trabajo y no tuve tiempo de revisión pero enseguida lo hago.
