### ISSUE TITLE
Traducir artículos de blogs destacados

### ISSUE THREAD

**Issue by francjp** [mozillahispano/noticias#7]
Buscar blogs interesantes sobre Mozilla que tengan artículos sobre Mozilla para traducir al español

**Comment by Anteojudo** [comment]
¡Hola chicos! Después de unos días sin leernos quería aparecerme por aquí para preguntar si puedo traducir ésta noticia liberada en la página de Mozilla Security: https://blog.mozilla.org/security/2015/08/11/expanded-malware-protection-in-firefox/
Creo que valdría la pena hablar sobre esto porque va a tono con el objetivo a cumplir con la nueva actualización de Firefox.
¡Saludos!

**Comment by francjp** [comment]
Hola @Anteojudo, podés hacer el borrador y cuando lo tengas listo avisar, y así lo publicamos?

Saludos.

**Comment by Anteojudo** [comment]
¡Hola chicos!
La nota ya está lista para ser revisada y publicada. ¡Disculpen la demora! :)
¡Saludos!

**Comment by Anteojudo** [comment]
Chicos, el texto del artículo está para revisión en wordpress: https://www.mozilla-hispano.org/wp-admin/post.php?post=39172&action=edit

**Comment by francjp** [comment]
Perdón imanol, he tenido un par de días que no pude entrar al dashboard... empiezo a publicar hoy y en estos días lo que hay pendiente

**Comment by Anteojudo** [comment]
¡Hola Franco, no hay drama che, estamos todos con nuestras cosas y se entiende! :)

**Comment by Anteojudo** [comment]
¡Hola chicos! Estoy realizando una traducción de la nueva publicación de The Mozzila Blog. Aquí el link: https://blog.mozilla.org/blog/2015/09/24/mozillas-vision-for-a-healthy-sustainable-web/#more-9036
Creo que en estos días va a estar. Dejo avisado :9

**Comment by francjp** [comment]
Imanol, creo que lo mejor sería abrir un issue nuevo por cada artículo para no confundir... decime si no podés abrirlo y lo abro yo y trato de asignartelo.

Saludos,

**Comment by jvadillo** [comment]
Cierro este issue, tal y como comenta Fran, se abrirá un issue por cada nuevo artículo a traducir.
¡Gracias!
