### ISSUE TITLE
El futuro de los complementos de Firefox

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/noticias#8]
Artículo sobre los cambios en el modelo de complementos de Firefox

https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

**Comment by Josexv1** [comment]
Ya estoy escribiendo algo. Dentro de un par de horas lo publico aquí para que lo revises.

**Comment by Josexv1** [comment]
@nukeador aqui esta el articulo para revisión. Avísame si tiene algo mal, o si le falta algo.
https://www.dropbox.com/s/c3jf3l0glbpxk7v/El%20futuro%20de%20los%20complementos%20en%20Firefox.odt?dl=0

**Comment by nukeador** [comment]
¿Lo puedes subir a un GDoc o algún sitio dónde el revisor lo pueda editar?

**Comment by nukeador** [comment]
¿Lo puedes subir a un GDoc o etherpad para que un revisor pueda editarlo?

**Comment by Josexv1** [comment]
Aquí tienes. https://drive.google.com/file/d/0BwFZK-AblEqYc2dIbkc2aW8yRnM/view?usp=sharing

**Comment by francjp** [comment]
Hola @josexv1, tienes cuenta en el WP de Mozilla Hispano??

Saludos.

**Comment by Josexv1** [comment]
Hola @francjp no, no tengo cuenta alli.

**Comment by francjp** [comment]
Ok, pasame email y si quieres algún nombre de usuario en particular para crearte una y que subas el borrador allí

**Comment by Josexv1** [comment]
Claro, jozhee[at]live.com usuario:diffusive si puedes me explicas un poco en el correo el proceso que se realiza para subir noticias.

**Comment by francjp** [comment]
Ya tienes usuario y acceso. Deberías haber recibido un email con los datos. Si no lo ves, revisa el Spam.

Respecto al proceso:
https://www.mozilla-hispano.org/documentacion/Noticias#C.C3.B3mo_colaborar
Si tienes alguna duda, puedes preguntar en el foro, esto lo dejamos para gestionar las tareas.

Saludos.

**Comment by francjp** [comment]
Publicado, mil gracias Jose
