### ISSUE TITLE
Actualizacion de WebMaker.

### ISSUE THREAD

**Issue by Josexv1** [mozillahispano/noticias#9]
Hola amigos, estoy escribiendo un articulo sobre la actualizacion de WebMaker y la salida del BETA para Android, pero no cuento con un dispositivo Android, Alguno puede bajar la APP y tomar algunas fotos utilizandolo? para subirlas al post. Aqui hay un post en ingles con algo de documentacion.
https://blog.mozilla.org/blog/2015/08/17/mozilla-webmaker-meet-the-world-2/

**Comment by nukeador** [comment]
Lo mejor es que para las dudas preguntes directamente en el foro de redacción y los comentarios aquí sean exclusivamente sobre el avance de la tarea, ya que no todo el mundo sigue todos los comentarios que se hacen aquí.

Un saludo.

**Comment by Josexv1** [comment]
Hola ya la entrada esta lista para ser revisada, solo falta acomodar las imágenes que están demasiado grandes porque las copie desde imgur, y como no puedo subir fotos bueno. El wp agrega un div especial, pero aun así no cambia el tamaño. Si creen que otra imagen se vería mejor, aquí les dejo una [galeria](http://imgur.com/a/Wszis) --- [vista previa](https://www.mozilla-hispano.org/?p=39188&preview=true)

**Comment by francjp** [comment]
Hola Jose, lo reviso y trato de publicarlo en estos días.

Las fotos las miro y te digo si necesito que me pases por mail los archivos en todo caso.

Saludos

**Comment by Josexv1** [comment]
Vale, igual están en el imgur, solo tienes que descargarlas desde ahí, y están casi que en 4k lol

**Comment by Josexv1** [comment]
Publicado: https://foro.mozilla-hispano.org/t/webmaker-para-android-ya-esta-aqui/21048/1 Cerrar issue.
